### PR TITLE
Add a Dataset Profile example (CO2 dataset)

### PR DESCRIPTION
**Pull request by bact**
Inspired from https://github.com/owid/co2-data/

Structurally and semantically validated against all tools here: https://github.com/spdx/spdx-3-model/blob/main/serialization/json_ld/validation.md

TODOs:
- [x] Valid JSON-LD
- [x] Parseable/make sense on https://json-ld.org/playground/
- [x] Pass validation/generation of [spdx3ToGraph](https://github.com/maxhbr/spdx3ToGraph)
- [x] Pass pyshacl
- [x] Pass check-jsonschema
- [x] Pass ajv

### CODE REVIEW

**Comment by bact** [comment]
Experiment notes:

- Successfully Validated with all the tools (`ajv`, `check-jsonschema`, `pyshacl`) listed at https://github.com/spdx/spdx-3-model/blob/main/serialization/json_ld/validation.md
- Warning messages of `ajv` and `check-jsonschema` sometimes are not very helpful
  - If there're warnings/errors, trying to remove some objects from your JSON. Once the smaller JSON got validated, gradually add few more.
  - `spdx3ToGraph` can be more handy to detect errors in the first runs as it can provide more useful error messages (use this https://github.com/maxhbr/spdx3ToGraph/pull/2 to get more exact location of error)
  - But `spdx3ToGraph` validation will not check the cardinality, you still have to use `ajv` or `check-jsonschema` for that. (The tool is meant primarily for visualization btw)
    - If maxCount is `*`, the data type must be an array
- A lot of errors found in this try (and in few other examples) is about serialized names. So if TODO in https://github.com/spdx/spdx-spec/issues/975 is completed, it will help a lot.

**Comment by bact** [comment]
This this how I put the license in this example. Does it advisable to do it like this?
(or does there a way to use `https://spdx.org/licenses/CC-BY-4.0` or `CC-BY-4.0` directly?)

```json
    {
      "type": "simplelicensing_LicenseExpression",
      "spdxId": "https://spdx.org/licenses/CC-BY-4.0",
      "creationInfo": "_:creationinfo",
      "simplelicensing_licenseExpression": "CC-BY-4.0",
      "simplelicensing_licenseListVersion": "3.24.0"
    }
```

**Comment by bact** [comment]
@rgopikrishnan91 this PR please Gopi

**Comment by bact** [comment]
@rgopikrishnan91 @bennetkl please kindly review.

**Review by bennetkl — APPROVED** [review]
Looks good, approved.

**Comment by bennetkl** [comment]
@kestewart   I believe you will have to merge, I don't have permission for this one.

**Comment by kestewart** [comment]
DIscussed in AI call.   Merging.

**Pull request merged**
