### PR TITLE
[WIP] Create simpleHRT-example.json

### PR DESCRIPTION
**Pull request by rgopikrishnan91**
This is a first attempt at writing an AI BOM. Need help with 
1. Checking the integrity of the example
2. How to add licensing information

This AI BOM is for the application available here https://github.com/githubharald/SimpleHTR/tree/master

@kestewart

### CODE REVIEW

**Comment by bact** [comment]
@rgopikrishnan91 I made a PR to your branch here https://github.com/rgopikrishnan91/spdx-examples/pull/1 to fix few JSON errors.

**Comment by bact** [comment]
For licensing information, I guess it will look more or less like this:

```json

    {
      "type": "Relationship",
      "spdxId": "urn:",
      "relationshipType": "concludedLicense",
      "from": "...",
      "to": "CC-BY-4.0",
      "creationInfo": "_:creationinfo",
    },
    {
      "type": "Relationship",
      "spdxId": "urn:",
      "relationshipType": "declaredLicense",
      "from": "...",
      "to": "CC-BY-4.0",
      "creationInfo": "_:creationinfo",
    }
```

`from` should be the id of the element that has the licenses

What I'm not sure is the `to` that should we use the SPDX short name of the license or should it be some kind of IRI?

**Comment by bact** [comment]
> My problem is I am not sure how to define custom licenses and I think the dataset here needs a custom license

Right. Maybe this one is going to be a complex example.

**Comment by bact** [comment]
I found that the dictionary entries is quite cumbersome for a big dictionary. Based on the work of Gopi's, I found that we have to have it like this...

```json
            "ai_hyperparameter": [
                {
                    "type": "DictionaryEntry",
                    "key": "cnn_kernel_vals",
                    "value": "[5, 5, 3, 3, 3]"
                },
                {
                    "type": "DictionaryEntry",
                    "key": "cnn_nfeature_vals",
                    "value": "[1, 32, 64, 128, 128, 256]"
                }
            ]
```

Hopefully we will soon not have to do this by hand....

**Comment by bact** [comment]
Btw, good news, this example is now passed the validation by spdx3ToGraph (see https://github.com/rgopikrishnan91/spdx-examples/pull/1 )

However, due to a very long string (few of them are values in dictionary entries), due to the constraint of JSON string, PlantUML is unable to draw the diagram properly (the diagram got cropped).

**Comment by bact** [comment]
For custom license, I think it will probably look like this:

```json
        {
            "type": "expandedlicensing_CustomLicense",
            "spdxId": "https://spdx.org/spdxdocs/CustomLicense-c63547c2-62e0-48ec-b98d-ff1b917d67db",
            "creationInfo": "_:creationinfo",
            "simplelicensing_licenseText": "This database may be used for non-commercial research purpose only. If you publish material based on this database, we request you to include a reference to paper. U. Marti and H. Bunke. The IAM-database: An English Sentence Database for Off-line Handwriting Recognition. Int. Journal on Document Analysis and Recognition, Volume 5, pages 39 - 46, 2002.",
            "expandedlicensing_isFsfLibre": false,
            "expandedlicensing_isOsiApproved": false
        },
        {
            "type": "Relationship",
            "spdxId": "https://spdx.org/spdxdocs/Relationship/declaredLicense-2c9563dc-baa1-4385-be02-ad671976a8aa",
            "creationInfo": "_:creationinfo",
            "relationshipType": "hasDeclaredLicense",
            "from": "https://my-first-aibom.com/IAMdataset",
            "to": "https://spdx.org/spdxdocs/CustomLicense-c63547c2-62e0-48ec-b98d-ff1b917d67db"
        },
        {
            "type": "Relationship",
            "spdxId": "https://spdx.org/spdxdocs/Relationship/concludedLicense-3bcfa4ce-6a65-46e8-bed1-18985211bb9e",
            "creationInfo": "_:creationinfo",
            "relationshipType": "hasConcludedLicense",
            "from": "https://my-first-aibom.com/IAMdataset",
            "to": "https://spdx.org/spdxdocs/CustomLicense-c63547c2-62e0-48ec-b98d-ff1b917d67db"
        },
```

The above snippet use [CustomLicense](https://spdx.github.io/spdx-spec/v3.0/model/ExpandedLicensing/Classes/CustomLicense/) but I think we can also use [SimpleLicensingText](https://spdx.github.io/spdx-spec/v3.0/model/SimpleLicensing/Classes/SimpleLicensingText/) as well.

**Comment by bact** [comment]
Now pass all the validations (JSON Schema and SHACL)

Available for review at
https://github.com/rgopikrishnan91/spdx-examples/pull/2

**Comment by zvr** [comment]
AFAIK you cannot split strings into different lines in JSON, so lines 1016-1039 produce a syntax error and they have to be converted to two lines.
The formatting is strange in other places, as well, with lots of whitespace in the middle of some strings.

**Comment by zvr** [comment]
For the licensing part, all licensing information is expressed via `Relationship`s. There are two `relationshipType`s that can be used: `hasDeclaredLicense` to record the licensing information found in the artifact and `hasConcludedLicense` to record what the data creator states that the artifact is licensed under. In both cases, a `Relationship` is needed, with `from` being an artifact and `to` being a license expression. 

For example, recording the conclusion that your dataset is under the `MIT` license might look like:
```json
{
  "spdxId": "https://my-first-aibom.com/rel-1",
  "type": "Relationship",
  "relationshipType": "hasConcludedLicense",
  "from": "https://my-first-aibom.com/IAMdataset",
  "to": "https://spdx.org/licenses/MIT",
  "creationInfo": "_:creationinfo"
}
```

If the license is not in the SPDX License List, you have to create a new `CustomLicense` and use a `Relationship` pointing to that one. For example:
```json
{
  "spdxId": "https://my-first-aibom.com/rel-2",
  "type": "Relationship",
  "relationshipType": "hasConcludedLicense",
  "from": "https://my-first-aibom.com/IAMdataset",
  "to": "https://my-first-aibom.com/LicenseRef-MyStrangeLicense",
  "creationInfo": "_:creationinfo"
},
{
  "spdxId": "https://my-first-aibom.com/LicenseRef-MyStrangeLicense",
  "type": "expandedlicensing_CustomLicense",
  "name": "LicenseRef-MyStrangeLicense",
  "simplelicensing_licenseText": "Anyone can use this dataset without any obligation.",
  "creationInfo": "_:creationinfo"
},
```

**Comment by bact** [comment]
I have tried to point the `to` of license relationships to `https://spdx.org/licenses/MIT` (and any URL in the SPDX licenses list), but SHACL validator tells that it has a wrong type (not a `License`).

**Comment by zvr** [comment]
Yes, the validator needs to know about every item in the SPDX License List.

Unfortunately, we do not yet generate such definitions for SPDXv3. We do generate for the SPDXv2 RDF, as you can see in https://github.com/spdx/license-list-data/blob/main/jsonld/CC-BY-4.0.jsonld. 

I've created an issue at the List Publisher about it.

Keep in mind, that even if we had this data, it would not be straightforward to use, since _which_ data you should be using depends on the value of the `licenseListVersion` property.

**Comment by bact** [comment]
Thank you @zvr that is very clear and very useful.

**Comment by bact** [comment]
As a workaround to complete the validation, my approach is to declare an `AnyLicenseInfo` element with an spdxId the same as the target license IRI. Once we have `ListedLicense` in SPDX 3 RDF, this workaround element will be removed.
See: https://github.com/spdx/spdx-examples/pull/84#issuecomment-2177842322

**Comment by rgopikrishnan91** [comment]
@bact @kestewart @zvr The example has now been modified to include all the comments and suggestions. Thank you both Art and Zvr for the help!

Key additions:
1. Added licensing info for all the dependencies. 
2. Removed concluded license for model and SimpleHRT as we cannot assertively say that (because the dataset has a non-commercial clause and the model is licensed under MIT)

Please approve if everything looks good. Thanks once again!

**Comment by bact** [comment]
Thank you.

Following the structure of examples of Software Profile, we may also like to rename the file/folder to something like:
`ai/example01/spdx3.0/simpleHTR.spdx.json`

**Comment by rgopikrishnan91** [comment]
@kestewart Can you please merge this if you are happy with it too?

**Comment by bact** [comment]
btw, we have both "simple*HRT*" and "simple*HTR*" here.

**Review by bennetkl — APPROVED** [review]
All changes in comments have been made, and example is approved

**Comment by rgopikrishnan91** [comment]
> btw, we have both "simple_HRT_" and "simple_HTR_" here.

Hey, I am not sure where you mean we have both version. Could you please point out so that I can fix it?

**Comment by bact** [comment]
@rgopikrishnan91 inside the BOM, we have "SimpleHTR" (handwritten text recognition). but in the filename, we have "SimpleHRT" (T and R swap).

I have put the PR to your repo here:

https://github.com/rgopikrishnan91/spdx-examples/pull/3

**Comment by rgopikrishnan91** [comment]
@bennetkl Hey can you merge it now? 

@bact Thanks a bunch!

**Comment by bennetkl** [comment]
Looks like Kate merged this one.

**Pull request merged**
